name: CI-E2E
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: lima
        run: |
          limactl start --tty=false --name=bpfdev template://ubuntu-lts
          limactl shell bpfdev exec -- hostname -I


