name: CI-E2E
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: lima
        run: |
          limactl start --tty=false --name=bpfdev --mount-writable=true template://ubuntu-lts

      - name: clone
        run: |
          limactl shell bpfdev exec -- sudo apt-get install git
          limactl shell bpfdev exec -- /usr/bin/bash -c "cd"
          limactl shell bpfdev exec -- sudo git clone -b E2E https://github.com/Atul-source/l3af-arch.git

      - name: run l3afd
        run: |
          limactl shell bpfdev exec -- /bin/bash -c "cd l3af-arch/dev_environment && sudo ./setup_linux_dev_env.sh"
          limactl shell bpfdev exec -- /bin/bash -c "cd e2e_test && ./test_suite.sh"
          exit 0
          limactl stop bpfdev
